const nome = "Lorena"

try {
  nome = "Fl√°via"
} catch(err) {
  console.log('Capturei um erro no try: ', err)
}

console.log(nome)

console.log('Fim')
